// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVw1-GgOkvIm5B5mwVOu2B1V0y2Z_RrTI',
    appId: '1:32991853700:web:1346d6144a84a406ae56d1',
    messagingSenderId: '32991853700',
    projectId: 'nhl-data-display-platform',
    authDomain: 'nhl-data-display-platform.firebaseapp.com',
    storageBucket: 'nhl-data-display-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPJGjdEVembo7f-KSQcdYZ409hHh2E2Q',
    appId: '1:32991853700:android:146a7bcbe3b99b17ae56d1',
    messagingSenderId: '32991853700',
    projectId: 'nhl-data-display-platform',
    storageBucket: 'nhl-data-display-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDmEMkjE9bm_c_l_Ioj3_lo_z638BmlFI',
    appId: '1:32991853700:ios:9d636f437bff1860ae56d1',
    messagingSenderId: '32991853700',
    projectId: 'nhl-data-display-platform',
    storageBucket: 'nhl-data-display-platform.firebasestorage.app',
    iosBundleId: 'com.example.nhlDataDisplayPlatformFrontend',
  );
}
